// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcZNSfj554sWIJPtvcMvMkV01WfOl1yW0',
    appId: '1:768720920142:web:069d927aba2ecf464c2d1f',
    messagingSenderId: '768720920142',
    projectId: 'savespot-7e6c9',
    authDomain: 'savespot-7e6c9.firebaseapp.com',
    storageBucket: 'savespot-7e6c9.firebasestorage.app',
    measurementId: 'G-5799B0ZZ4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7oHF0qv-Xee2fKUj-5ZDNh3iSwITNPXE',
    appId: '1:768720920142:android:d849f07e59f495bd4c2d1f',
    messagingSenderId: '768720920142',
    projectId: 'savespot-7e6c9',
    storageBucket: 'savespot-7e6c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn-q2S9PP0yYBp4nfuvwkTYyhtPH89KAc',
    appId: '1:768720920142:ios:d4dc706b2528e00e4c2d1f',
    messagingSenderId: '768720920142',
    projectId: 'savespot-7e6c9',
    storageBucket: 'savespot-7e6c9.firebasestorage.app',
    iosClientId: '768720920142-cpqcf8gpmlstfbum24j4chcj3dbmm4aq.apps.googleusercontent.com',
    iosBundleId: 'com.example.savespotProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn-q2S9PP0yYBp4nfuvwkTYyhtPH89KAc',
    appId: '1:768720920142:ios:d4dc706b2528e00e4c2d1f',
    messagingSenderId: '768720920142',
    projectId: 'savespot-7e6c9',
    storageBucket: 'savespot-7e6c9.firebasestorage.app',
    iosClientId: '768720920142-cpqcf8gpmlstfbum24j4chcj3dbmm4aq.apps.googleusercontent.com',
    iosBundleId: 'com.example.savespotProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcZNSfj554sWIJPtvcMvMkV01WfOl1yW0',
    appId: '1:768720920142:web:9c8688192a8d839f4c2d1f',
    messagingSenderId: '768720920142',
    projectId: 'savespot-7e6c9',
    authDomain: 'savespot-7e6c9.firebaseapp.com',
    storageBucket: 'savespot-7e6c9.firebasestorage.app',
    measurementId: 'G-2B1X5FWE6Q',
  );
}
